<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enquiry</name>
   <tag></tag>
   <elementGuidId>40bd22e3-333b-4743-8944-d5f11d0b3f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-us > a.nav-bar-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='contact-us']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enquiry&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85c935b7-c42c-4418-8083-13d911272d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-bar-link</value>
      <webElementGuid>ac5bd7eb-6027-466d-a36c-baeb3651d28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/enquiry</value>
      <webElementGuid>62f36a05-10fe-46cb-bc7e-9238c6f3d0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enquiry</value>
      <webElementGuid>c83a15b6-5acf-492a-bb01-b98c170f76bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us&quot;)/a[@class=&quot;nav-bar-link&quot;]</value>
      <webElementGuid>d9af2a8d-bf92-4379-9535-70aedff36980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='contact-us']/a</value>
      <webElementGuid>0a8f3376-800c-4487-b8d2-bf78b09eb8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enquiry')]</value>
      <webElementGuid>6a7a0361-7983-4bbb-826f-4cb14377f13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[1]/following::a[1]</value>
      <webElementGuid>d7bfa793-3141-4cf1-b49f-c4e697fad4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programs'])[1]/following::a[2]</value>
      <webElementGuid>6be401b0-dfbf-41fb-bd96-4648aff22ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='READ MORE'])[1]/preceding::a[1]</value>
      <webElementGuid>79ec764f-74f1-455b-8b55-6eb6611b2001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROGRAMS'])[1]/preceding::a[2]</value>
      <webElementGuid>d6f7f70f-cec7-40b4-8169-e8a145275ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enquiry']/parent::*</value>
      <webElementGuid>7544f005-1af6-481e-9a5b-3ce101b25ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/enquiry')]</value>
      <webElementGuid>2c28c05d-3f49-4316-ad5a-b2d390702ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>42ffbf8e-4329-473f-86a0-4ccf8ae6cac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/enquiry' and (text() = 'Enquiry' or . = 'Enquiry')]</value>
      <webElementGuid>8939176e-af3a-44e1-ad35-6b5bc31fbd6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
