<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PREVIOUS</name>
   <tag></tag>
   <elementGuidId>0e91154d-b885-4be1-a3b9-6dd935ed94a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pagination-previous-next-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/section/div[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Previous page&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58de430b-9aba-487f-9c45-a159078c8901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-previous-next-link</value>
      <webElementGuid>c0324d0f-c8c1-422b-af99-b80ca6fa6005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aaf4a4e3-2e11-443f-9827-7b950f3c6975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c42252c-ff7f-4883-97a4-263d7fc0f19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e2cf59a-5ea3-4f32-ba6d-922e836fb4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous page</value>
      <webElementGuid>245b9fd6-dde4-4624-a3e1-2c24e64fbc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>19d660e7-388b-4b19-9b5a-60812d40e10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt; PREVIOUS</value>
      <webElementGuid>00d0da8b-d3b4-484f-966a-82d5ae05e7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-component-wrapper&quot;]/section[@class=&quot;program-container d-flex flex-column align-items-center mb-5&quot;]/section[@class=&quot;programs-container d-flex flex-column align-items-center mb-5&quot;]/div[4]/ul[@class=&quot;pagination-container&quot;]/li[@class=&quot;pagination-previous-next-container&quot;]/a[@class=&quot;pagination-previous-next-link&quot;]</value>
      <webElementGuid>06eeaf66-d935-4ff0-bd7e-933ceeebced0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/div[4]/ul/li/a</value>
      <webElementGuid>5652737a-06c7-4ff2-9c8a-aaee38b1f36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'&lt; PREVIOUS')]</value>
      <webElementGuid>52a85f34-d1ca-4ce0-b078-4012c6da65d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View More'])[1]/following::a[1]</value>
      <webElementGuid>479c2c77-c0cd-40ea-8955-4bec142917ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More'])[4]/following::a[1]</value>
      <webElementGuid>23cd8fc5-237b-418e-8f4d-8c1a015acfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT >'])[1]/preceding::a[3]</value>
      <webElementGuid>8d7f2028-d5f8-49b2-b8b9-a4614c97627a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[4]</value>
      <webElementGuid>b1885c02-5885-4f51-b08f-77f036a6e6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt; PREVIOUS']/parent::*</value>
      <webElementGuid>8a242c0c-61bb-4d65-89d8-501617679477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>5b194776-c4f1-46d2-8d20-baa2ac5c7c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '&lt; PREVIOUS' or . = '&lt; PREVIOUS')]</value>
      <webElementGuid>d189ac66-0679-4ff8-8383-72791a9dc4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
