<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Enquiry List</name>
   <tag></tag>
   <elementGuidId>ac6c5421-22c5-464c-a7e6-e171323448aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program-apply-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='program-apply-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add to Enquiry List&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>761f3800-0c54-4ce8-ac25-6c6da34ac7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>program-apply-button</value>
      <webElementGuid>6fe3530b-ec9b-40ba-8099-4c5524ade7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-self-center</value>
      <webElementGuid>811c7af3-d77a-4f6c-9825-4bbbbc40c889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Enquiry List</value>
      <webElementGuid>80b84df7-fb7a-471a-b08f-1e35197fbc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;program-apply-button&quot;)</value>
      <webElementGuid>3c15bea7-6d82-4b05-a032-52e63626d19e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='program-apply-button']</value>
      <webElementGuid>6328a3c2-4fa6-4ded-a0f3-0d9d0602618b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/div[6]/div/button</value>
      <webElementGuid>70ed055f-f878-47a1-a488-0add2ee381d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrum Product Owner Certification under Scrum Study (SPOC)'])[2]/following::button[1]</value>
      <webElementGuid>a1ed2ee9-97d8-4c45-beee-cb6d682005a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::button[1]</value>
      <webElementGuid>27bc6e77-a7c3-4198-a1b8-7ba2948a5fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated:'])[1]/preceding::button[1]</value>
      <webElementGuid>fad88c13-8e78-46d9-b495-d6328d684f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAMBER SKILLS'])[3]/preceding::button[1]</value>
      <webElementGuid>6da652bb-3341-4c52-a16c-09805c60c203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to Enquiry List']/parent::*</value>
      <webElementGuid>47e4f55d-56b2-48ac-a01e-668227bda4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>120bd23b-30d2-473e-bd69-588679671843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'program-apply-button' and (text() = 'Add to Enquiry List' or . = 'Add to Enquiry List')]</value>
      <webElementGuid>a198658a-830d-49c9-8b44-c9305b1b4d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
