<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View More</name>
   <tag></tag>
   <elementGuidId>b4bd043b-7352-4994-b53e-42f092b144a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-more-programs-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='view-more-programs-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;View More&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dfa9402-00c0-45c1-a601-37af90854e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-more-programs-btn</value>
      <webElementGuid>7ee0ef74-199b-4723-bfa5-ccf5f8a431af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View More</value>
      <webElementGuid>506b204b-70d0-4e30-a7af-ffc5a6ed98b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-more-programs-btn&quot;)</value>
      <webElementGuid>0ef464a7-4527-4c2c-92b6-59e8a612c388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='view-more-programs-btn']</value>
      <webElementGuid>2c8bec4e-c453-4269-a683-913f88536507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/button</value>
      <webElementGuid>458a306b-ebbf-47c6-bd00-8d92d05252af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More'])[6]/following::button[1]</value>
      <webElementGuid>09383212-1dc9-477c-879b-09ad5ee05aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA101 Ayeshwery'])[1]/following::button[2]</value>
      <webElementGuid>420ae4d9-5d6e-4139-9a89-b5a299d1b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; PREVIOUS'])[1]/preceding::button[1]</value>
      <webElementGuid>cf944686-bd8f-49d8-b756-be8095a494a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT >'])[1]/preceding::button[1]</value>
      <webElementGuid>621d2087-7f0b-4ce8-9e4b-eda5114234b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View More']/parent::*</value>
      <webElementGuid>e4741263-d930-45cc-8097-40c92f72b826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/button</value>
      <webElementGuid>612c75f0-94a8-4557-9214-ea0bf9955d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'view-more-programs-btn' and (text() = 'View More' or . = 'View More')]</value>
      <webElementGuid>c68d5d33-3ac9-4d3c-8635-fd57cc8b6faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
