<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_ENQUIRY</name>
   <tag></tag>
   <elementGuidId>5d21c324-daea-4a46-b59d-16b616000924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-component-body.d-flex.flex-column.align-items-center > div.main-component-header > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;ENQUIRY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d98c7da1-6c7b-4964-9042-c708f1b200d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENQUIRY</value>
      <webElementGuid>bcb27954-5539-4ba2-b514-c22de5ac05aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-component-wrapper&quot;]/div[@class=&quot;main-component-body d-flex flex-column align-items-center&quot;]/div[@class=&quot;main-component-header&quot;]/h1[1]</value>
      <webElementGuid>02bd11ad-050b-4c98-b2ef-fb061e975c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/h1</value>
      <webElementGuid>3f829e51-73e7-43a7-bde2-c224879194c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated:'])[1]/following::h1[1]</value>
      <webElementGuid>e296613a-616e-42ef-80be-0475b4f86d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Enquiry List'])[1]/following::h1[1]</value>
      <webElementGuid>40b651d5-a1eb-4fd5-ac9b-7c05e94867a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reach Out to Us'])[1]/preceding::h1[1]</value>
      <webElementGuid>8c3a7c49-856e-4ee6-854c-cd4cd4defdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENQUIRY']/parent::*</value>
      <webElementGuid>423b2315-9231-49ec-945f-4a01e2a6b953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h1</value>
      <webElementGuid>3cb1476e-4347-465e-888d-a0a17626b341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'ENQUIRY' or . = 'ENQUIRY')]</value>
      <webElementGuid>977fe382-41e7-4d85-bf00-aa6973e66c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
