<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__full_name</name>
   <tag></tag>
   <elementGuidId>cf57851f-408a-434a-8be1-1e7214d38ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-item-input-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-item-input-white']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ahmad Ahmad&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a154e7c-76f7-41ea-ace4-c3e385bddfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a76b429-c815-4897-ba8d-362d1d5068ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>94f9fa0d-05a5-4c35-8d00-c25c149beca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-item-input-white</value>
      <webElementGuid>f5589800-681b-4117-a7c9-007772d20024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ahmad Ahmad</value>
      <webElementGuid>c577e962-2b74-4e1d-a1b3-0be2ae16b9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us-form&quot;)/div[@class=&quot;form-body-wrapper&quot;]/div[@class=&quot;form-fill-div&quot;]/div[@class=&quot;form-item&quot;]/input[@id=&quot;form-item-input-white&quot;]</value>
      <webElementGuid>c202fed1-a2f4-4471-a461-e900aad16afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-item-input-white']</value>
      <webElementGuid>8cb3effa-ad4e-49c4-b974-a251e8dde73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-us-form']/div[3]/div/div/input</value>
      <webElementGuid>73c724de-3b66-4a2f-8ae6-e4475e44d6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7d35c868-6be8-4f60-9ce1-1e1dc33aea2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full_name' and @id = 'form-item-input-white' and @placeholder = 'Ahmad Ahmad']</value>
      <webElementGuid>cb111e9c-d84a-46cf-af1b-8f6b3bcc8148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
