<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_test100-Ayehswery_program_1</name>
   <tag></tag>
   <elementGuidId>2cb273d9-12c7-48e2-a9f9-145e5f60be20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CA101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CA101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;CA101 Ayeshwery&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ed20c8f-f51d-4e2d-8637-94a852a5b10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f1ed32ab-72f9-4ba7-8806-9ade8d00ead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>program</value>
      <webElementGuid>3ef70b55-9db4-472e-a765-a33668685c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CA101</value>
      <webElementGuid>c001f0b9-0dd1-4571-88fa-d069052c0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CA101</value>
      <webElementGuid>d9cfceb8-caa6-4539-ae7c-a41a108aec96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CA101&quot;)</value>
      <webElementGuid>6c272ff6-7980-4648-8341-d798941b2f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CA101']</value>
      <webElementGuid>d11e3429-c0eb-4651-8aac-c254a183023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checklist-item']/div[6]/input</value>
      <webElementGuid>1bdeb386-8e6b-49eb-9d95-59bc51674aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>98a0851a-549b-492a-b3f5-c6afd2ef67bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'program' and @id = 'CA101']</value>
      <webElementGuid>fff7bcd3-298f-4ed6-8e76-5eee4e7643ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
