<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_test100-Ayehswery_program</name>
   <tag></tag>
   <elementGuidId>d05889c0-1c41-4a16-acde-a01bdb42fc68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LA108</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LA108']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LA108</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>243ebc3d-0c20-46c4-9827-9ef8454adfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>206f5261-ecac-4d58-a2c6-4f24d31a5bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>program</value>
      <webElementGuid>c6b5e042-65a4-4ee8-84fd-b11f46e5b0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LA108</value>
      <webElementGuid>b6ed1fd0-196b-4420-836e-74ad90f5f58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LA108</value>
      <webElementGuid>7125bd8b-4e86-4187-9ce1-2fa46b0ade1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LA108&quot;)</value>
      <webElementGuid>f6dbbbe3-ae73-4c6f-9053-814f46bbee0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LA108']</value>
      <webElementGuid>127a5ee7-de95-44fc-a326-65058da6c130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checklist-item']/div[5]/input</value>
      <webElementGuid>9d2db896-ad4f-4201-bf16-13eafdd3ed63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/input</value>
      <webElementGuid>8b2823eb-cd79-481b-9f2f-9249dff7a019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'program' and @id = 'LA108']</value>
      <webElementGuid>f6b38a9f-99d1-4b77-b9be-bd045895b0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LA105']</value>
      <webElementGuid>c259630e-6c53-49c0-bc46-b590b3d696ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checklist-item']/div[2]/input</value>
      <webElementGuid>4c25f652-4a3d-4a3c-8cc1-1fda392f4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>6f9e0feb-ae1d-4811-b914-ea422fa64d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'program' and @id = 'LA105']</value>
      <webElementGuid>1b91a9fa-5688-4a51-b041-43b3577d0ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
