<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_2</name>
   <tag></tag>
   <elementGuidId>1327fd71-67c3-4d3a-9bc9-ce309a7761c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/section/div[4]/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;2&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>db013087-2693-46f5-b3ce-7ff031ae4812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-page</value>
      <webElementGuid>3e54cce3-829f-4631-9d65-304d57aecdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e63c4678-5326-4a4a-8cdf-c95fc464bef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-component-wrapper&quot;]/section[@class=&quot;program-container d-flex flex-column align-items-center mb-5&quot;]/section[@class=&quot;programs-container d-flex flex-column align-items-center mb-5&quot;]/div[4]/ul[@class=&quot;pagination-container&quot;]/li[@class=&quot;pagination-page&quot;]</value>
      <webElementGuid>fb5b112a-6a63-4f2e-9a24-1acc7c649b13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/section/div[4]/ul/li[3]</value>
      <webElementGuid>d519a30d-7277-41de-8c4a-970b7f55459f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; PREVIOUS'])[1]/following::li[2]</value>
      <webElementGuid>2300b00d-9511-40c4-86a3-d58a9f09caf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View More'])[1]/following::li[3]</value>
      <webElementGuid>9f8171de-5c87-4bac-bd5e-1e632118e5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT >'])[1]/preceding::li[1]</value>
      <webElementGuid>f1f7f2ba-38d3-4474-8e0d-3052357ace36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::li[2]</value>
      <webElementGuid>870ff2ba-dac5-49c2-9fd6-f1acbbe1dc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[3]</value>
      <webElementGuid>62185cf6-af0f-43a1-8c23-42069d7a8f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '2' or . = '2')]</value>
      <webElementGuid>96da9b25-13e3-4f5d-9db3-62ef49f52597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
